#!/bin/bash

mkdir -p pki/{cacerts,certs,private}
pki --gen --type rsa --size 4096 --outform pem > pki/private/ca-key.pem
pki --self --ca --lifetime 3650 --in pki/private/ca-key.pem --type rsa --dn "CN=VPN root CA" --outform pem > pki/cacerts/ca-cert.pem